INSERT IGNORE INTO recipes (id, name, instructions, cooking_time_in_minutes, created_at, updated_at) VALUES
  (1, 'Spaghetti Bolognese', 'Cook spaghetti. Brown ground beef with onions and garlic. Add tomato sauce and simmer. Combine with pasta.', 45, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (2, 'Chicken Stir Fry', 'Slice chicken and vegetables. Stir fry chicken until cooked. Add sauce and cook until veggies are tender-crisp.', 25, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (3, 'Beef Tacos', 'Brown ground beef with taco seasoning. Warm tortillas. Fill with beef, lettuce, cheese, and salsa.', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (4, 'Vegetable Curry', 'Sauté onions, garlic, and ginger. Add curry paste, vegetables, and coconut milk. Simmer until vegetables are soft.', 35, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (5, 'Pancakes', 'Mix flour, milk, eggs, and baking powder into a smooth batter. Pour onto hot pan and flip when bubbles appear.', 15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (6, 'Grilled Cheese Sandwich', 'Butter bread slices. Place cheese between slices and cook in a pan until bread is golden and cheese is melted.', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (7, 'Tomato Soup', 'Sauté onions and garlic. Add tomatoes and broth. Simmer and blend until smooth. Adjust seasoning.', 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (8, 'Roast Chicken', 'Season whole chicken with salt, pepper, and herbs. Roast in oven until juices run clear and skin is crispy.', 90, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (9, 'Garlic Butter Shrimp', 'Melt butter in pan. Add garlic and shrimp. Cook until shrimp turn pink. Finish with lemon juice and parsley.', 12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (10, 'Caesar Salad', 'Toss chopped romaine with Caesar dressing, croutons, and Parmesan. Top with grilled chicken if desired.', 15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (11, 'Margherita Pizza', 'Spread tomato sauce on pizza dough. Top with fresh mozzarella and basil leaves. Bake until crust is crisp.', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (12, 'Chili Con Carne', 'Brown ground beef with onions and garlic. Add beans, tomatoes, and chili spices. Simmer until thick and rich.', 60, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (13, 'Fried Rice', 'Cook rice and let cool. Stir fry vegetables and scrambled eggs, then add rice and soy sauce. Fry until heated through.', 25, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (14, 'Lemon Herb Salmon', 'Season salmon with salt, pepper, lemon juice, and herbs. Bake or pan-sear until flesh is opaque and flaky.', 18, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (15, 'Mac and Cheese', 'Cook pasta. Make cheese sauce with butter, flour, milk, and cheese. Combine pasta with sauce and bake if desired.', 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (16, 'Greek Salad', 'Chop tomatoes, cucumbers, onion, and bell pepper. Toss with olives, feta cheese, olive oil, and oregano.', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (17, 'Chicken Noodle Soup', 'Simmer chicken with carrots, celery, and onions in broth. Add noodles and cook until tender.', 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (18, 'Banana Bread', 'Mix mashed bananas with flour, sugar, eggs, and butter. Pour into loaf pan and bake until a toothpick comes out clean.', 55, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (19, 'Stuffed Peppers', 'Fill bell peppers with a mixture of cooked rice, ground meat, and seasoning. Bake until peppers are tender.', 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (20, 'Veggie Omelette', 'Whisk eggs. Pour into hot pan. Add chopped vegetables and cheese. Fold omelette when eggs are set.', 12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (21, 'BBQ Pulled Pork Sandwich', 'Slow cook pork with BBQ sauce until tender. Shred meat and serve on buns with extra sauce.', 240, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (22, 'Caprese Salad', 'Layer tomato slices, fresh mozzarella, and basil. Drizzle with olive oil and balsamic vinegar. Season with salt.', 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (23, 'Mushroom Risotto', 'Sauté mushrooms and onions. Toast rice in pan, then slowly add broth while stirring until creamy and tender.', 35, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (24, 'Fish and Chips', 'Coat fish fillets in batter and deep fry until golden. Serve with fried potatoes and tartar sauce.', 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (25, 'Lentil Soup', 'Simmer lentils with onions, carrots, celery, and spices in broth until lentils are soft and soup is thick.', 45, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
  
  INSERT IGNORE INTO recipes (id, name, instructions, cooking_time_in_minutes, created_at, updated_at) VALUES
  (26, 'Chicken Parmesan', 'Bread chicken cutlets, pan fry until golden, top with marinara and mozzarella, then bake until cheese is melted.', 35, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (27, 'Eggplant Lasagna', 'Slice eggplant, roast until tender, then layer with tomato sauce and cheese. Bake until bubbling.', 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (28, 'Shrimp Scampi Pasta', 'Cook pasta. Sauté shrimp in butter, garlic, and lemon. Toss shrimp and sauce with pasta.', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (29, 'Turkey Meatloaf', 'Mix ground turkey with breadcrumbs, egg, and seasoning. Shape into loaf and bake until cooked through.', 55, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (30, 'Butternut Squash Soup', 'Roast squash, then simmer with onions, broth, and spices. Blend until smooth and creamy.', 45, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (31, 'Chicken Fajitas', 'Marinate chicken strips with lime and spices. Sear with onions and peppers and serve with tortillas.', 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (32, 'Spinach and Feta Stuffed Chicken', 'Slice pockets into chicken breasts, stuff with spinach and feta, then bake until chicken is cooked.', 35, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (33, 'Sushi Rice Bowl', 'Cook sushi rice, top with sliced cucumber, avocado, nori, and cooked fish or tofu, then drizzle with soy sauce.', 25, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (34, 'BBQ Chicken Pizza', 'Spread BBQ sauce over pizza dough, top with cooked chicken, onions, and cheese. Bake until crust is crisp.', 22, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (35, 'Thai Green Curry', 'Sauté curry paste with coconut milk, add chicken or tofu and vegetables, and simmer until cooked through.', 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (36, 'Beef Stroganoff', 'Brown beef strips with onions and mushrooms, add broth and sour cream, and serve over egg noodles.', 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (37, 'Chickpea Buddha Bowl', 'Roast chickpeas and vegetables, serve over grains with a tahini or yogurt sauce.', 35, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (38, 'Fish Tacos with Slaw', 'Pan-sear fish with spices, serve in tortillas with cabbage slaw and a lime yogurt sauce.', 25, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (39, 'Chicken Pot Pie', 'Cook chicken and vegetables in a creamy sauce, pour into a dish, top with pastry, and bake until golden.', 60, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (40, 'Ramen Noodle Bowl', 'Simmer broth with soy and aromatics, add noodles, vegetables, and boiled egg just before serving.', 25, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (41, 'Veggie Quesadillas', 'Fill tortillas with cheese and sautéed vegetables, cook in a pan until tortillas are browned and cheese melts.', 15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (42, 'Baked Ziti', 'Cook ziti, mix with tomato sauce and cheese, then bake until bubbly and lightly browned.', 35, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (43, 'Tuna Salad Sandwich', 'Mix canned tuna with mayo, celery, and seasoning. Serve on bread with lettuce and tomato.', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (44, 'Overnight Oats', 'Combine oats, milk, yogurt, and fruit in a jar. Refrigerate overnight and serve cold.', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (45, 'Chicken Caesar Wrap', 'Fill a tortilla with Caesar salad and sliced grilled chicken, then roll tightly into a wrap.', 12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (46, 'Falafel Wrap', 'Stuff warm pita or flatbread with falafel, lettuce, tomato, cucumber, and tahini or yogurt sauce.', 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (47, 'Roasted Veggie Pasta', 'Roast mixed vegetables, toss with cooked pasta, olive oil, garlic, and Parmesan.', 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (48, 'Pumpkin Pancakes', 'Mix pumpkin puree into pancake batter with warm spices, cook on a hot griddle until golden.', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (49, 'Quinoa Salad with Lemon Dressing', 'Cook quinoa and cool. Toss with chopped vegetables, herbs, and a lemon-olive oil dressing.', 25, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (50, 'Chocolate Mug Cake', 'Mix flour, cocoa, sugar, and milk in a mug and microwave until just set in the center.', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

